### PR TITLE
Fixed mixed imports

### PR DESCRIPTION
**Pull request by kLabz**
Fixed imports like:
```
import x, { y, z } from "a"
```

Still not passing `DefinitelyTyped` "test", do you have any other form of test atm?

---
This change is [Reviewable](https://reviewable.io/reviews/firefalcom/ts2hx/15)

### CODE REVIEW

**Comment by crazyjul** [comment]
Right now, we only work on getting this to work with Babylon.js.

I would be happy to include your file if it's not a private one.

We haven't updated any test so far, as we tried it first. But now, as the result are good for us, we'll try to test it seriously.

Thanks for the patch

**Comment by kLabz** [comment]
I am generating externs for [devextreme-react](https://www.npmjs.com/package/devextreme-react).

DefinitelyTyped is just the test explained in README.md, and is quite complete but we do not handle all cases atm.

**Comment by kLabz** [comment]
Are you planning on creating a PR to the parent project once this works?

**Comment by gogoprog** [comment]
@kLabz Yes this is the plan

**Pull request merged**
